### ISSUE TITLE
Are you planning to bring a dashboard?

### ISSUE THREAD

**Issue by MZRCode** [SiebeBaree/Coinz#14]
- I feature request is not about a problem.
- I believe it will be better and more beautiful if there is a dashboard.
- It would be great if there was a logic to sell items through the dashboard on the site! Or we could make some server settings from this dashboard.
- I wish you good coding with the hope that this feature will come.

**Comment by SiebeBaree** [comment]
@MZRCode We are planning to include a dashboard but this is not the priority at the moment. A simple dashboard is coming in the next update but you can just view general information and can't interact with the bot yet. In a future update we plan to release a dashboard that you can play games in, sell items, ...

**Comment by MZRCode** [comment]
I believe there will be some really great updates and i can't wait. I wish
you good coding. 🙂

19 Kas 2023 Paz 16:29 tarihinde Siebe Baree ***@***.***> şunu
yazdı:
